code --install-extension aaron-bond.better-comments
code --install-extension ahmadalli.vscode-nginx-conf
code --install-extension antfu.array-index-inlay
code --install-extension antfu.auto-npx
code --install-extension antfu.file-nesting
code --install-extension antfu.goto-alias
code --install-extension antfu.iconify
code --install-extension antfu.open-in-github-button
code --install-extension antfu.pnpm-catalog-lens
code --install-extension antfu.theme-vitesse
code --install-extension antfu.unocss
code --install-extension antfu.where-am-i
code --install-extension astro-build.astro-vscode
code --install-extension bradlc.vscode-tailwindcss
code --install-extension bruceyuhb.hsl-preview
code --install-extension burkeholland.simple-react-snippets
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension cipchk.cssrem
code --install-extension codeium.windsurfpyright
code --install-extension codezombiech.gitignore
code --install-extension davidanson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension dotjoshjohnson.xml
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension editorconfig.editorconfig
code --install-extension equimper.react-native-react-redux
code --install-extension esbenp.prettier-vscode
code --install-extension expo.vscode-expo-tools
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.code-runner
code --install-extension github.vscode-pull-request-github
code --install-extension golang.go
code --install-extension gruntfuggly.todo-tree
code --install-extension jasonnutter.search-node-modules
code --install-extension jock.svg
code --install-extension johnsoncodehk.vscode-tsconfig-helper
code --install-extension kevinkyang.auto-comment-blocks
code --install-extension kisstkondoros.vscode-gutter-preview
code --install-extension llvm-vs-code-extensions.lldb-dap
code --install-extension lokalise.i18n-ally
code --install-extension mariusalchimavicius.json-to-ts
code --install-extension mhutchie.git-graph
code --install-extension mikestead.dotenv
code --install-extension mpontus.tab-cycle
code --install-extension mrmlnc.vscode-json5
code --install-extension ms-ceintl.vscode-language-pack-zh-hans
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-python.vscode-python-envs
code --install-extension ms-vscode.hexeditor
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension msjsdiag.vscode-react-native
code --install-extension naumovs.color-highlight
code --install-extension nicholashsiang.vscode-vue3-snippets
code --install-extension openai.chatgpt
code --install-extension oven.bun-vscode
code --install-extension oxc.oxc-vscode
code --install-extension p42ai.refactor
code --install-extension pflannery.vscode-versionlens
code --install-extension philsinatra.nested-comments
code --install-extension pranaygp.vscode-css-peek
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.liveserver
code --install-extension sdras.vue-vscode-snippets
code --install-extension shardulm94.trailing-spaces
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension simonhe.common-intellisense
code --install-extension simonhe.export-what
code --install-extension simonhe.to-ts-type
code --install-extension simonhe.v-component-prompter
code --install-extension simonhe.vscode-css-selector
code --install-extension simonhe.vscode-generate-comment
code --install-extension simonsiefke.svg-preview
code --install-extension sporiley.css-auto-prefix
code --install-extension steoates.autoimport
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension svelte.svelte-vscode
code --install-extension swiftlang.swift-vscode
code --install-extension tamasfe.even-better-toml
code --install-extension techer.open-in-browser
code --install-extension typescriptteam.native-preview
code --install-extension unifiedjs.vscode-mdx
code --install-extension usernamehw.errorlens
code --install-extension vincaslt.highlight-matching-tag
code --install-extension vitest.explorer
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vue.volar
code --install-extension xabikos.javascriptsnippets
code --install-extension yoavbls.pretty-ts-errors
code --install-extension you612.vue-file-analyzer
code --install-extension yzhang.markdown-all-in-one
code --install-extension zignd.html-css-class-completion
