tap "alienator88/cask"
tap "buo/cask-upgrade"
tap "dteoh/sqa"
tap "epk/epk"
tap "homebrew/bundle"
tap "homebrew/services"
tap "jysperm/leftover-scanner"
tap "krtirtho/apps"
tap "lihaoyun6/tap"
tap "localsend/localsend"
tap "mac-cleanup/mac-cleanup-py"
tap "mrkai77/cask"
tap "netdcy/flowvision"
tap "oven-sh/bun"
tap "pablopunk/brew"
tap "zackelia/formulae"
# Interpreted, interactive, object-oriented programming language
brew "python@3.13"
# Shell extension to jump to frequently used directories
brew "autojump"
# Programmable completion for Bash 3.2
brew "bash-completion"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Control and limit battery charging on Apple Silicon MacBooks
brew "batt"
# Parser generator tool and incremental parsing library
brew "tree-sitter"
# Emacs dependency management
brew "cask"
# Mozilla CA bundle for Python
brew "certifi"
# Secure runtime for JavaScript and TypeScript
brew "deno"
# Like neofetch, but much faster because written mostly in C
brew "fastfetch"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Fast and simple Node.js version manager
brew "fnm"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Alternative to top/htop
brew "glances"
# Improved top (interactive process viewer)
brew "htop"
# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"
# Add GitHub support to git on the command-line
brew "hub"
# CLI wrapper for basic network utilities on macOS - ip command
brew "iproute2mac"
# Helps you navigate your file system faster by learning your habits
brew "jump"
# Fast and simple video downloader
brew "lux"
# Keep your Mac's application settings in sync
brew "mackup"
# Apple Silicon Monitor Top written in Golang
brew "mactop"
# Mac App Store command-line interface
brew "mas"
# TCP port scanner, scans entire Internet in under 5 minutes
brew "masscan"
# Port scanning utility for large networks
brew "nmap"
# Command-line Git information tool
brew "onefetch"
# Package compiler and linker metadata toolkit
brew "pkgconf"
# Monitor data's progress through a pipe
brew "pv"
# Python version management
brew "pyenv"
# Pyenv plugin to manage virtualenv
brew "pyenv-virtualenv"
# Interpreted, interactive, object-oriented programming language
brew "python@3.12"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Authy/Google Authenticator like TOTP CLI tool written in Go
brew "totp-cli"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Internet file retriever
brew "wget"
# JavaScript package manager
brew "yarn"
# Dumb downloader that scrapes the web
brew "you-get"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# UNIX shell (command interpreter)
brew "zsh"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Python cleanup script for macOS
brew "mac-cleanup/mac-cleanup-py/mac-cleanup-py"
# Incredibly fast JavaScript runtime, bundler, transpiler and package manager - all in one.
brew "oven-sh/bun/bun"
# Get the battery level of all your devices on your Mac.
cask "airbattery"
# iOS App Store alternative
cask "altserver"
# Inspect application bundles
cask "apparency"
# iOS device backup software
cask "bbackupp"
# Desktop password and login vault
cask "bitwarden"
# OpenAI's official ChatGPT desktop app
cask "chatgpt"
# Tool to list all active shortcuts of the current application
cask "cheatsheet"
# Continuation of Clash Verge - A Clash Meta GUI based on Tauri
cask "clash-verge-rev"
# Write, edit, and chat about your code with AI
cask "cursor"
# Teamwork app by Alibaba Group
cask "dingtalk"
# Elegant tool built for coding
cask "easydevo"
# Dictionary and translator app
cask "easydict"
# Launcher for *Epic Games* games
cask "epic-games"
cask "font-fira-code"
cask "font-meslo-lg-nerd-font"
cask "font-sf-mono-nerd-font"
# GIT client
cask "fork"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Desktop client for GitHub repositories
cask "github"
# Web browser
cask "google-chrome"
# HTML editor
cask "hbuilderx"
# Free and open-source media player
cask "iina"
# Tool to optimise images to a smaller size
cask "imageoptim"
# Tool for multi-language users
cask "input-source-pro"
# Menu bar manager
cask "jordanbaird-ice"
# File archiver
cask "keka"
# Helper application for the Keka file archiver
cask "kekaexternalhelper"
# Open-source cross-platform alternative to AirDrop
cask "localsend"
# Window manager
cask "loop"
# Utility to extend trackpad functionality
cask "middleclick"
# Tool to control external monitor brightness & volume
cask "monitorcontrol"
# Smooths scrolling and set mouse scroll directions independently
cask "mos"
# Database administration and development tool
cask "navicat-premium-lite"
# Finds large, unwanted files and deletes them
cask "omnidisksweeper"
# System and utility switches
cask "only-switch"
# Verify system files structure, run miscellaneous maintenance and more
cask "onyx"
# Replacement for Docker Desktop
cask "orbstack"
# Utility to uninstall apps and remove leftover files from old/uninstalled apps
cask "pearcleaner"
# Image viewer
cask "pictureview"
# Apple Notes extension
cask "pronotes"
# HTTP debugging proxy
cask "proxyman"
# Quick Look plug-in that renders source code with syntax highlighting
cask "qlcolorcode"
# Quick Look generator for Markdown files
cask "qlmarkdown"
# Quick Look plugin for plaintext files without an extension
cask "qlstephen"
# Thumbnails, static previews, cover art and metadata for video files
cask "qlvideo"
# Quick Look plugin for JSON files
cask "quicklook-json"
# Quick Look generator for Adobe Swatch Exchange files
cask "quicklookase"
# A lightweight and high-performance screen recorder for macOS.
cask "quickrecorder"
# Control your tools with a few keystrokes
cask "raycast"
# Standalone client for sing-box, the universal proxy platform
cask "sfm"
# Music streaming service
cask "spotify"
# System monitor for the menu bar
cask "stats"
# Video game digital distribution service
cask "steam"
# Quicklook extension for source files
cask "syntax-highlight"
# Messaging app with a focus on speed and security
cask "telegram"
# Pin any window to the top of your screen.
cask "topit"
# PKG software package uninstall tool
cask "uninstallpkg"
# Virtual machines UI using QEMU
cask "utm"
# Open-source code editor
cask "visual-studio-code"
# Create, manage, and run virtual machines
cask "vmware-fusion"
# JavaScript IDE
cask "webstorm"
# Free messaging and calling application
cask "wechat"
# Wechat DevTools for Official Account and Mini Program development
cask "wechatwebdevtools"
# Connect to Windows
cask "windows-app"
# Agentic IDE powered by AI Flow paradigm
cask "windsurf"
# All-in-one office service platform in Chinese
cask "wpsoffice-cn"
# Mind mapping and brainstorming tool
cask "xmind@beta"
mas "AdBlocker", id: 1018301773
mas "Command X", id: 6448461551
mas "Developer", id: 640199958
mas "DevHub", id: 6476452351
mas "Hand Mirror", id: 1502839586
mas "Hush", id: 1544743900
mas "Immersive Translate", id: 6447957425
mas "Keynote 讲演", id: 409183694
mas "MindNode Next", id: 6446116532
mas "Numbers 表格", id: 409203825
mas "Pages 文稿", id: 409201541
mas "Quantumult X", id: 1443988620
mas "SnippetsLab", id: 1006087419
mas "Tampermonkey", id: 6738342400
mas "TestFlight", id: 899247664
mas "Xcode", id: 497799835
vscode "ahmadalli.vscode-nginx-conf"
vscode "antfu.array-index-inlay"
vscode "antfu.file-nesting"
vscode "antfu.goto-alias"
vscode "antfu.iconify"
vscode "antfu.open-in-github-button"
vscode "antfu.pnpm-catalog-lens"
vscode "antfu.smart-clicks"
vscode "antfu.theme-vitesse"
vscode "antfu.unocss"
vscode "antfu.vite"
vscode "antfu.where-am-i"
vscode "astro-build.astro-vscode"
vscode "bradlc.vscode-tailwindcss"
vscode "bruceyuhb.hsl-preview"
vscode "christian-kohler.npm-intellisense"
vscode "christian-kohler.path-intellisense"
vscode "cipchk.cssrem"
vscode "codeium.codeium"
vscode "csstools.postcss"
vscode "davidanson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "donjayamanne.githistory"
vscode "dsznajder.es7-react-js-snippets"
vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "evils.uniapp-vscode"
vscode "formulahendry.auto-close-tag"
vscode "formulahendry.auto-rename-tag"
vscode "formulahendry.code-runner"
vscode "gantoreno.vscode-vercel-theme"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.vscode-pull-request-github"
vscode "ipatalas.vscode-postfix-ts"
vscode "jasonnutter.search-node-modules"
vscode "jock.svg"
vscode "johnsoncodehk.vscode-tsconfig-helper"
vscode "kevinkyang.auto-comment-blocks"
vscode "kisstkondoros.vscode-gutter-preview"
vscode "loczek.next-js-ts-snippets"
vscode "lokalise.i18n-ally"
vscode "mariusalchimavicius.json-to-ts"
vscode "mhutchie.git-graph"
vscode "mikestead.dotenv"
vscode "mpontus.tab-cycle"
vscode "mrmaoddxxaa.create-uniapp-view"
vscode "ms-azuretools.vscode-docker"
vscode "ms-ceintl.vscode-language-pack-zh-hans"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-vscode.live-server"
vscode "ms-vscode.vscode-typescript-next"
vscode "msjsdiag.vscode-react-native"
vscode "naumovs.color-highlight"
vscode "p42ai.refactor"
vscode "pflannery.vscode-versionlens"
vscode "philsinatra.nested-comments"
vscode "pranaygp.vscode-css-peek"
vscode "rangav.vscode-thunder-client"
vscode "redhat.vscode-yaml"
vscode "ritwickdey.liveserver"
vscode "rust-lang.rust-analyzer"
vscode "sdras.vue-vscode-snippets"
vscode "shardulm94.trailing-spaces"
vscode "shd101wyy.markdown-preview-enhanced"
vscode "simonhe.common-intellisense"
vscode "simonhe.export-what"
vscode "simonhe.fast-jump"
vscode "simonhe.generate-variable-names"
vscode "simonhe.log"
vscode "simonhe.to-ts-type"
vscode "simonhe.unot"
vscode "simonhe.v-component-prompter"
vscode "simonhe.vscode-css-selector"
vscode "simonhe.vscode-generate-comment"
vscode "simonhe.vscode-script"
vscode "simonhe.vscode-tailwind-magic"
vscode "simonsiefke.svg-preview"
vscode "sporiley.css-auto-prefix"
vscode "steoates.autoimport"
vscode "streetsidesoftware.code-spell-checker"
vscode "stylelint.vscode-stylelint"
vscode "suhelmakkad.shadcn-ui"
vscode "tamasfe.even-better-toml"
vscode "tauri-apps.tauri-vscode"
vscode "techer.open-in-browser"
vscode "uni-helper.uni-app-schemas-vscode"
vscode "uni-helper.uni-app-snippets-vscode"
vscode "uni-helper.uni-cloud-snippets-vscode"
vscode "uni-helper.uni-helper-vscode"
vscode "uni-helper.uni-highlight-vscode"
vscode "uni-helper.uni-ui-snippets-vscode"
vscode "unifiedjs.vscode-mdx"
vscode "usernamehw.errorlens"
vscode "vincaslt.highlight-matching-tag"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vitest.explorer"
vscode "vscode-icons-team.vscode-icons"
vscode "vue.volar"
vscode "wakatime.vscode-wakatime"
vscode "wallabyjs.console-ninja"
vscode "wix.vscode-import-cost"
vscode "xabikos.javascriptsnippets"
vscode "yoavbls.pretty-ts-errors"
vscode "yzhang.markdown-all-in-one"
vscode "zignd.html-css-class-completion"
